apiVersion: v1
kind: Service

metadata: 
  name: zabbix-wrapper
  labels: 
    name: zabbix-wrapper
spec: 
  type: NodePort
  ports:
   # the port that this service should serve on
   - port: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: zabbix-wrapper
  type: LoadBalancer
